### ISSUE TITLE
PNG cover images don't work on iPad with Apple Books

### ISSUE THREAD

**Issue by gbnewby** [gutenbergtools/ebookmaker#234] opened 2024-08-08 00:24 UTC
See https://www.gutenberg.org/ebooks/30728 or other books that don't include a cover page image for an example.

EBM correctly creates a random cover page in JPEG format. However, the format of the cover page within the EPUB is PNG. 8038495381949947165_30728-cover.png in this example.

We have a verified report that viewing this on a current model iPad with the Apple "Books" app (iPad Air 11-inch (M2) running iOS 17.6) does not show the cover page in the library index (image attached). 

It seems that instead of PNG  these books should have a JPEG cover image.

![IMG_6182](https://github.com/user-attachments/assets/2589911d-3c31-49d8-8277-50a8fb0c67d8)

**Comment by eshellman** [comment] 2024-08-08 08:21
try this one: (remove the .zip extension)
[pg30728-images-3.epub.zip](https://github.com/user-attachments/files/16539974/pg30728-images-3.epub.zip)

**Comment by asylumcs** [comment] 2024-08-08 11:22
I've forwarded it to the user.

**Comment by eshellman** [comment] 2024-08-08 15:42
that epub tests if a the dimensions of the cover png make a difference.

**Comment by asylumcs** [comment] 2024-08-08 17:00
The user reports the new epub shows the geometric-shapes cover. To be honest, my "something isn't right" alarm is going off. Her iPad shows a mix of blue-icon book covers and regular book covers. She seems to think the blue ones are quite old. Gut feel: image dimensions do not matter especially based on the recommended dimensions that are quite large. Perhaps she simply has old epubs for the ones that show the blue covers. I'm going to ask her to download a modern eBook from PG that uses the png cover image.

**Comment by asylumcs** [comment] 2024-08-09 03:19
I asked her to download 74204 because I knew it would be new and not cached on her iPad. Her inconclusive  description of what happens leads me to think we probably don't need to change anything. Perhaps those "blue covers" were ones that she had on an older iPad that Apple transferred to her new device. Here is her report:

> When I actually downloaded the book (which I now realize is Don Quixote!), something very odd happened. I went to the downloads folder on my ipad, clicked on the file that had downloaded, and it opened with at first, fleetingly, a plain brown cover, then the pink geometric cover immediately replaced the brown cover. Then when I went to Books, and closed the “book” and reopened it, I got a flash of the brown cover which was fleetingly replaced by the pink geometric cover. Now, when I quit Books and go back in, the pink geometric cover is all I see.
> 
> I have never experienced that before. Ever.
> 
> When I say “fleetingly,” I mean it’s as fast as one snap of your fingers. VERY fast.

**Comment by asylumcs** [comment] 2024-08-09 14:12
Update: thinking the ebooks she had with blue covers might just be very old, I asked her to download recent versions. Here is her report:

> Sure, I will download at least one of the blue icon books again. Hang on…ok, I downloaded The Gifts of Asti, by Andre Norton. It came in with a plain gray cover, which changed to the geometric one in the downloads folder just like Don Quixote did yesterday. Then when I opened Books, it was the plain gray cover, but after I opened the book, and closed it again, it was geometric. So I quit Books and went back in. The cover of The Gifts of Asti is geometric, in Books, at the moment.
> 
> But the cover of Oneness, that I downloaded yesterday, is plain brown today. It’s no longer geometric. I will try opening it and see what happens…Interesting. I clicked on the book to open it. Inside, the cover popped up—geometric. I closed the book—brown cover. I quit out of Books and went back in. Brown cover. 
> 
> At least it’s not the blue icon!

**Comment by asylumcs** [comment] 2024-08-09 14:14
She also mentioned this:

> Someone on the apple support site was claiming that apple fixed it so that any books not purchased through the apple store would disappear from people’s libraries, but that’s not true. I have all the books.

Maybe something is going on with Apple. But we would have heard about this from other users, right?

**Comment by asylumcs** [comment] 2024-08-09 14:16
I've asked her to send me one of the Epubs that is showing the blue cover if she can figure out how to do it. I would like to figure out what's going on.

**Comment by asylumcs** [comment] 2024-08-10 01:33
Seems to me this issue can be closed without action. If the blue covers cannot be reproduced, then we have no way to know if we've fixed anything. The user agrees. She writes "Please thank everyone at PG who tried to figure out what is going on. I appreciate their willingness to try."

**Comment by eshellman** [comment] 2024-08-11 19:36
Is there any downside to increasing the size to comply with the apple requirement?

**Comment by gbnewby** [comment] 2024-08-11 21:06
It sounds like that would be a good idea.

**Comment by eshellman** [comment] 2024-08-12 15:42
Given that the DP guidelines https://www.pgdp.net/wiki/DP_Official_Documentation:PP_and_PPV/Post-Processing_FAQ#Information_for_all_types_of_cover suggest 1600 wide , it seems that our generated covers should be that size.

**Comment by eshellman** [comment] 2024-08-12 22:30
I suspected the png width because current Apple Books guidelines specify a minimum width of 1400 pixels. The newest Apple devices have higher resolution screens, so that could be why we haven't seen this before. PNG files can upscale poorly when they have text in them; JPG files upscale with less complaints.

Generating the geometric covers at 1600x2400 instead of 1200x1800 should be painless, the filesize should not even change.

**Closed** 2024-09-20 14:10 UTC
