### ISSUE TITLE
Error running 11.4 on website

### ISSUE THREAD

**Issue by mannyack** [gutenbergtools/ebookmaker#91] opened 2021-08-28 00:03 UTC
Output log:

unzipping /htdocs/ebookmaker/cache/20210827160336/ll4_ebook.zip
Input file: ll4.html
EbookMaker 0.11.4
WARNING:root:Gutenberg Database is inactive because psycopg2 not installed
Traceback (most recent call last):
  File "/var/www/.local/share/virtualenvs/ebookmaker-A6HCkzTJ/bin/ebookmaker", line 18, in <module>
    EbookMaker.main ()
  File "/var/www/.local/share/virtualenvs/ebookmaker-A6HCkzTJ/lib/python3.6/site-packages/ebookmaker/EbookMaker.py", line 534, in main
    job.url = os.path.join(absoutputdir, output_files['epub.images'])
  File "/var/www/.local/share/virtualenvs/ebookmaker-A6HCkzTJ/lib/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/var/www/.local/share/virtualenvs/ebookmaker-A6HCkzTJ/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

**Comment by eshellman** [comment] 2021-08-28 19:18
Duplicate of #89. You were right about it not being Windows related.

**Closed by eshellman** 2021-08-28 19:18 UTC
