### ISSUE TITLE
Errors in automatically generated HTML files 

### ISSUE THREAD

**Issue by okrick** [gutenbergtools/ebookmaker#228] opened 2024-06-03 23:44 UTC
I added the images and HTML omitted from #13913 by the previous DP PPer by using the generated HTML file as a template.  I was surprised that there were several issues with the PG CSS boilerplate as reported by the  W3C HTML markup validator (http://validator.w3.org).   Improperly formatted comments in the CSS was the primary issue.

Further, the \<body> tag did not meet PG's standard of being on a distinct line.

I regard this as low priority as this only affects someone who wants to use a generated HTML file as a template--unless the buggy CSS adversely impacts the eBooks.

**Comment by eshellman** [comment] 2024-06-04 13:50
generated HTML is not intended to be used a a source file- you'll get duplicate metatags and duplicated boilerplate. Nor does it pay attention to any DP guidelines.

But... I can't reproduce your issue and I'm puzzled by "Improperly formatted comments in the CSS" as there are no comments in  the boilerplate CSS. https://github.com/gutenbergtools/ebookmaker/blob/c2e4704f1af59716058d366caf16177254f9b86c/src/ebookmaker/writers/TemplateStrings.py#L16-L83

**Comment by okrick** [comment] 2024-06-04 16:00
The \<body> tag is a PG guideline that PG's Errata Workbench enforces.

The above is not the CSS from the generated file.  [pg13913-images.zip](https://github.com/user-attachments/files/15567095/pg13913-images.zip]  This HTML file was from right-clicking on the "Read online (web)" link [https://www.gutenberg.org/ebooks/13913.html.images]. 

Are you certain the above template is used to create HTML from text files?  Nearly every line of the CSS I saw was commented and the multiple-line comments were not correctly formatted.  There was no HTML among the files I downloaded through the Errata Workbench, so I downloaded and used the generated file.

**Comment by eshellman** [comment] 2024-06-04 17:10
let's make sure we're talking about the same thing. a css comment looks like this:
`/* This is a comment */`

**Comment by eshellman** [comment] 2024-06-04 17:13
I'm unfamiliar with the Errata Workbench - perhaps it's mucking with the CSS?

**Comment by asylumcs** [comment] 2024-06-04 17:52
The Errata Workbench does not modify the CSS.

**Comment by okrick** [comment] 2024-06-04 17:57
I agree.  The Errata Workbench doesn't modify anything in the uploaded files.  It does move them from the old system to Github.

**Comment by eshellman** [comment] 2024-06-05 14:36
Source HTML is parsed, normalized, and updated to HTML5, accessibility markup is added, header and footer are replaced, metatags and boilerplate css are added to make the web version.

@okrick If you were surprised, then probably there is some documentation that is missing or needs improvement. Suggestions?

**Comment by okrick** [comment] 2024-06-05 19:28
Here is an example of a generated HTML file with multiple-line CSS comments.
[pg212-images.zip](https://github.com/user-attachments/files/15595516/pg212-images.zip)

Every one of the multi-line CSS comments had to be removed for the file to pass the [W3C HTML markup validator](http://validator.w3.org/) on the file I was adding images to.  I have no idea why this file passes the W3C HTML markup validator.  I wish I had saved the earlier file.

Please note that the <body> tag in this file is not on a line of its own in violation of PGs policy.  PGs Errata Workbench will show errors should one try to upload this.

**Comment by eshellman** [comment] 2024-06-06 13:55
the multiline css comments in  the file you've posted are correctly formatted. If the errata workbench is flagging them as errors it is a bug that should be fixed.

**Comment by eshellman** [comment] 2024-06-06 15:37
@okrick can you provide details on how to reproduce the html validator errors? When I try it I get no errors.

**Comment by eshellman** [comment] 2024-06-06 17:05
thanks!

**Closed by eshellman** 2024-06-06 17:05 UTC
